### PR TITLE
Ss test2

### PR DESCRIPTION
**Pull request by AnonSS**

### CODE REVIEW

**Review by igoodenow — CHANGES_REQUESTED** [review]
In one of the backup folder declaration statements, you have backupf as one of the folders. Is that on purpose?

**Comment by AnonSS** [comment]
@igoodenow  Yes.

**Comment by igoodenow** [comment]
merging to main

**Comment by igoodenow** [comment]
done

**Comment by igoodenow** [comment]
@shahramsobhani  you decide if you want to delete the branch

**Pull request merged**
